### ISSUE TITLE
CCPN10 での OSGeo.JP 発表内容イメージ

### ISSUE THREAD

**Issue by hfu** [OSGeo-jp/ccpn10#1]
最初の議論の材料として、次のような発表メッセージの案を提示させてください。

- [ベクトルタイルは重要な技術](https://qiita.com/hfu/items/6d1a07c56b48f1441535)であり、**多様な主体**による**持続的**なベクトルタイル供給が行われることが地理空間情報活用推進のために望ましく、その観点から、OSGeo 財団日本支部は、可能な範囲で国連ベクトルタイルツールキットを支援していきたい。
- 国連ベクトルタイルツールキットの普及と維持を支援するために、OSGeo 財団日本支部は国連ベクトルタイルツールキットのパートナーとして、１２月１日にモラトゥワでのワークショップを開催する。

発表に使える時間や機材など、まだ明確になっていないと理解していますが、コメントなどいただければ幸いです。

**Comment by hfu** [comment]
これ、私がモラツワ基調講演の前哨戦として日本語で資料を作ればいいんですね。作ってみます！

**Comment by wata909** [comment]
発表時間、機材について特に連絡はありませんが、いつものようにパワポ＋デモといった所かと思います。
個人的には、ツールキットの概要と、それを使ったデモ、地理院地図との重ね合わせ、といったことができればいいかなと思っています。

**Comment by hfu** [comment]
ありがとうございます。デモ、その延長で地理院タイルとも重なり合う、という話にもっていけるといいということですね。１２月２日の FOSS4G Asia 2018 用の研修セットから、１１月１５日までにできているところを取り分けて、デモ用のネタを作るという感じでいきたいと思います。

作業進みましたら、多分このスレッドを使って共有します！

**Comment by hfu** [comment]
デモを想定し、地理院タイルと重ね合わせて効果の高い、オープンなベクトルデータのお勧めがありましたら教えてください！

**Comment by wata909** [comment]
国土数値情報の一部が引用明記で使えるので、まずはその辺が妥当ではないかと思います。
既に地理院地図にのっていますがDID人口集中地区や小学校区は、粒度も細かすぎず、良いのではないかと思います。
逆に、ベクトルタイルの性能限界を試すという意味では、土地利用細分メッシュが面白いかもしれ無いと思います。
http://nlftp.mlit.go.jp/ksj/

自分の周りのデータでは、迅速測図の点データ
https://github.com/wata909/habs_test

土壌図
https://soil-inventory.dc.affrc.go.jp/download5.html

あたりが面白いかも。ただ土壌図は、スタイリングがちょっと面倒ですね…

**Comment by wata909** [comment]
あと、胆振地震の崩壊地のデータも、現場活用ということではいいと思いました。

喜多さんの
https://koukita.github.io/2018_09_06_atumatyou/

地理院さんの
http://www.gsi.go.jp/BOUSAI/H30-hokkaidoiburi-east-earthquake-index.html#10

**Comment by hfu** [comment]
ありがとうございます。興味深いなと思いましたので、縮尺5万分の１農耕地包括土壌図の全国一括のデータを、国連ベクトルタイルツールキットの手法を使ってベクトルタイルに変換してみました。

https://maputnik.github.io/editor/?style=https://hfu.github.io/dojo-style/style.json#11.54/33.7441/135.4028

最小ズームレベルは7、最大ズームレベルは12とし、ズームレベル12の時だけフルの属性にアクセスできます。ズームレベル7から12まで一貫して使えるのは統群コードで、これを code という名前の属性にしています。

スタイリングはまだですが、デモの際のちょっとしたアクセントになるよう、少しスタイリングしてみたいですね。

変換のコードは https://github.com/hfu/dojo に置いてあります。

本来、このデータは minzoom=11 とするのが技術的には正しそうなデータなのですが、概略を掴んでもらうため、無理やり minzoom=7 あたりまで引っ張って、小さいポリゴンから間引いています。タイルの最大サイズを 256KB と決め、それを超える場合には小さなポリゴンから削除していく設定にしています。結果として、名古屋あたりで、小さなポリゴンが多いところはざっくりと抜けてしまう症状が出てしまっているようです。本来、地図情報レベルが適切な別のデータでカバーするべきところでしょう。（いずれ、考えたいと思います。）

折を見て、少し進めてみたいと思いますし、できれば色々な方にスタイリングを試してみていただきたいです。

**Comment by hfu** [comment]
（１）国連ベクトルタイルツールキットの意義すなわちツールキットへの支援理由
（２）支援の具体例としての、FOSS4G Asia 2018 ワークショップの紹介
（３）技術の具体的な例示としての、土壌図の地理院タイルへの重ね合わせ事例
というような筋で、ご提案深めていきたいと思います。

**Comment by hfu** [comment]
縮尺20万分の1土壌図・縮尺5万分の1農耕地包括土壌図（農業・食品産業技術総合研究機構農業環境変動研究センター）ベクトルタイルをアップデートしました。昨日と比べ、20万のデータを加え、ざっくり色付けをしました。やはり、地図学的に言って、基本図項目は塗りの手前に来るべきですよね。つまり、ベクトルが必要だということですね。シュッとした地図を作るには、それだと思います。https://hfu.github.io/dojo-style/

**Comment by hfu** [comment]
プレゼンテーションが完成し、[ccpn10 のサイトに掲載](https://maps.gsi.go.jp/pn/meeting_partners/data/20181115/7.pdf)されましたので、クローズします。

ありがとうございました！
